name: build-sphinx-to-gh-pages

env:
  GITHUB_ACTOR: xiangxu
  GITHUB_REPOSITORY: iasonliu/iasonliu.github.io
  GITHUB_TOKEN: ${{ secrets.SPHINX_GITHUB_SECRET }}

on:
  push:
    branches: [ main ]


jobs:

  build_sphinx_job:
    runs-on: ubuntu-latest
    container: debian:buster-slim

    steps:

      - name: Get prerequisites and clone repository
        env:
          GITHUB_TOKEN: ${{ secrets.SPHINX_GITHUB_SECRET }}
        run: |
          set -x
          apt-get update
          apt-get install -y git
          git clone "https://iasonliu:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" .
        shell: bash

      - name: Run build script for Sphinx pages
        env:
          GITHUB_TOKEN: ${{ secrets.SPHINX_GITHUB_SECRET }}
        run: "docs/build.sh"
        shell: bash